# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8310e26e37f21517bf11cbe30e5abd5cf06359e2ca9bea74a89c8d82f4922a5396c015d59da32fbd9cc8f9e6ad772b2517e22be020016c4db7bebdc5aec004b2

test:
  secret_key_base: 95075d53531564c19e1873585c16405dc827972d841eb0550da7acfcb114240d300a33b6c40e43e7c3058a94d3c8480cf4bd283bd05cdd76026f4c844f306942

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
